csv_path: ../data/tracklet_keypoints.csv
embeddings_path: ../data/tracklet_id_embeddings.csv
num_neighbors: 10
max_spatial_distance: null
max_time_gap: 100
max_time_gap_past: 25
edge_attributes:
- kp_0_distance
- kp_1_distance
- kp_2_distance
- kp_3_distance
- id_distance
- t_gap
num_tracks: 12
set_exact_track_count: true
set_exact_active_tracklets_per_frame: false
embeddings_attribute_prefix: embedding
node_attributes:
- tracklet_length
t_min: null 
t_max: null 
