csv_path: /Users/lalitm/Desktop/github/lalitlab/tracklet_stitching/data/tracklet_keypoints.csv
embeddings_path: /Users/lalitm/Desktop/github/lalitlab/tracklet_stitching/data/tracklet_id_embeddings.csv
num_neighbors: 10
max_spatial_distance: null
max_time_gap: 100
max_time_gap_past: 25
edge_attributes:
- kp_0_distance
- kp_1_distance
- kp_2_distance
- kp_3_distance
- id_distance
- t_gap
num_tracks: 12
set_exact_track_count: true
set_exact_active_tracklets_per_frame: false
embeddings_attribute_prefix: embedding
node_attributes:
- tracklet_length
t_min: null #0
t_max: null #2500
pinned_nodes:
- 1
pinned_nodes_false:
- 67
- 69
- 76
- 77
- 88
- 101
- 102
- 103
- 115
- 3961
- 3962
- 3963
- 6114
- 14363
- 129
- 10275
- 19868
- 14405
- 19872
- 11581
- 131
- 132
- 133
- 134
- 136
- 5184
- 6871
- 8136
- 8137
- 8138
- 9413
- 9414
- 14408
- 14410
- 14412
- 19885
- 19895
- 19897
- 19898
pinned_chains:
- - 2
  - 7
  - 10
  - 6103
  - 11
  - 14
  - 16
  - 23
  - 27
  - 31
  - 35
  - 40
  - 49
  - 51
  - 58
  - 62
  - 68
  - 3955
  - 71
  - 92
  - 97
  - 8724
  - 106
  - 109
  - 6867
  - 3970
  - 122
- - 3946
  - 3
  - 50
  - 55
  - 5167
  - 59
  - 3952
  - 3953
  - 65
  - 74
  - 111
  - 114
  - 118
  - 121
  - 124
- - 4
  - 87
- - 5161
  - 5
  - 14335
  - 14336
  - 19
  - 26
  - 28
  - 32
  - 117
- - 5162
  - 30
  - 6860
  - 39
  - 78
  - 89
  - 93
  - 3969
  - 112
  - 113
  - 116
  - 120
- - 8
  - 41
  - 43
  - 5165
  - 47
  - 63
  - 3954
  - 70
  - 91
  - 94
- - 9
  - 73
  - 90
- - 12
  - 54
  - 108
- - 13
  - 42
  - 44
  - 45
  - 46
  - 48
  - 52
  - 80
  - 83
  - 84
  - 86
  - 95
  - 130
- - 22
  - 75
  - 6111
  - 79
  - 82
  - 135
- - 24
  - 56
weights_data:
  Node Selection tracklet_length_weight: -45.157746779462414
  Node Selection tracklet_length_constant: 0.39564195850747474
  Edge Selection kp_0_distance_regular_weight: -17.141706235547602
  Edge Selection kp_0_distance_regular_constant: -0.0
  Edge Selection kp_1_distance_regular_weight: 16.609824462118826
  Edge Selection kp_1_distance_regular_constant: -0.0
  Edge Selection kp_2_distance_regular_weight: 8.833844851838474
  Edge Selection kp_2_distance_regular_constant: -0.0
  Edge Selection kp_3_distance_regular_weight: 14.842748199563095
  Edge Selection kp_3_distance_regular_constant: -0.0
  Edge Selection id_distance_regular_weight: 0.37874474001419506
  Edge Selection id_distance_regular_constant: -0.0
  Edge Selection t_gap_regular_weight: 4.06852766481755
  Edge Selection t_gap_regular_constant: 0.3956419585059817
  Appear_weight: -0.0
  Appear_constant: 0.9739062321617963
  Disappear_constant: 0.999999964503971
